// Enforce the JavaScript conventions in STYLE.md and a strict correctness baseline. snake_case is
// allowed because many identifiers mirror Stratum, RPC, native, and configuration contracts.

import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";
import globals from "globals";

export default [
  {
    ignores: [
      "build/**",
      "build-platforms-hold/**",
      "node_modules/**",
      "release*/**",
      "**/*.bundle.cjs",
      "coverage/**",
      "perf-evidence/**",
      "test-artifacts/**",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{js,mjs}"],
    plugins: {"@stylistic": stylistic},
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {...globals.node},
    },
    rules: {
      // STYLE.md formatting (the code already follows these -> near-zero-churn guards).
      "@stylistic/indent": ["error", 2, {SwitchCase: 1}],
      "@stylistic/brace-style": ["error", "1tbs", {allowSingleLine: true}],
      "@stylistic/object-curly-spacing": ["error", "never"],
      "@stylistic/quotes": ["error", "double", {avoidEscape: true}],
      "@stylistic/semi": ["error", "always"],
      "@stylistic/no-trailing-spaces": "error",
      "@stylistic/eol-last": ["error", "always"],
      // STYLE.md declarations.
      "no-var": "error",
      "prefer-const": "error",
      "strict": ["error", "global"],
      "camelcase": "off",
      // strict correctness baseline. null:ignore keeps the intentional `== null`/`!= null` idiom
      // (matches null AND undefined) -- the only loose-equality the code relies on.
      "eqeqeq": ["error", "always", {null: "ignore"}],
      "no-unused-vars": ["error", {argsIgnorePattern: "^_", varsIgnorePattern: "^_"}],
      "no-implicit-globals": "error",
      "no-throw-literal": "error",
      "array-callback-return": "error",
      "accessor-pairs": "error",
      "block-scoped-var": "error",
      "curly": ["error", "all"],
      "default-case": "error",
      "default-case-last": "error",
      // checkJs's noPropertyAccessFromIndexSignature intentionally requires brackets at dynamic
      // protocol/config boundaries; ESLint's syntax-only dot rule contradicts that stronger check.
      "dot-notation": "off",
      "grouped-accessor-pairs": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-caller": "error",
      "no-constructor-return": "error",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-else-return": ["error", {allowElseIf: false}],
      "no-empty-function": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-floating-decimal": "error",
      "no-implied-eval": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-assign": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-object-constructor": "error",
      "no-return-assign": "error",
      "no-proto": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-template-curly-in-string": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "prefer-object-has-own": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "radix": "error",
      "symbol-description": "error",
      "unicode-bom": ["error", "never"],
      "yoda": "error",
    },
  },
  {
    files: ["**/*.mjs"],
    languageOptions: {sourceType: "module"},
  },
];
